Update pre-commit

diff --git a/scripts-hooks/pre-commit b/scripts-hooks/pre-commit
--- a/scripts-hooks/pre-commit
+++ b/scripts-hooks/pre-commit
@@ -1,38 +1,55 @@
-#!/bin/sh
-
-# Required modules install
-# ------
-# npx install-peerdeps --dev eslint-config-airbnb
-# yarn add prettier prettier-eslint prettier-eslint-cli prettier-stylelint --dev --exact
-# yarn add stylelint-config-standard husky --dev --exact
+#!/bin/bash
 
 # ------
-# ESLint Checking using script
+# ESLint + JEST Checking using script
 #
 # If git is reporting that your prettified files are still modified
 # after committing, you may need to add a post-commit script
 # to update git's index as described in this issue.
-#
-# @see https://prettier.io/docs/en/precommit.html#option-5-bash-script
-#
-jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')
-[ -z "$jsfiles" ] && exit 0
 
-for file in $jsfiles
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "js$")
+if [[ "$STAGED_FILES" = "" ]]; then
+    exit 0
+fi
+
+for FILE in $STAGED_FILES
 do
-  # we only want to lint the staged changes, not any un-staged changes
-  git show ":$file" | ./node_modules/.bin/eslint --stdin --stdin-filename "$file"
-  if [ $? -ne 0 ]; then
-    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
-    # exit with failure status
+  $(yarn bin)/eslint --quiet --max-warnings 0 "$FILE"
+  if [[ "$?" == 0 ]]; then
+    echo -e "\t\033[32mESLint Passed: $FILE\033[0m"
+  else
+    echo -e "\t\033[41mESLint Failed: $FILE\033[0m"
     exit 1
   fi
 done
 
+# get spec files from staged files if exists
+TESTS_FILES=()
+for FILE in $STAGED_FILES
+do
+  BASENAME=${FILE%/*}
+  FILENAME=${FILE##*/}
+  FILENAME=${FILENAME%%.*}
+  TESTFILE="$BASENAME/tests/$FILENAME.spec.js"
+  if [ -f $TESTFILE ]; then
+    TESTS_FILES+=($TESTFILE)
+  fi
+done
+
+# pass tests
+$(yarn bin)/jest --env=jsdom --bail ${TESTS_FILES[@]}
+if [[ "$?" == 0 ]]; then
+  echo -e "\t\033[32mJest Tests Passed\033[0m"
+else
+  echo -e "\t\033[41mJest Tests Failed\033[0m"
+  exit 1
+fi
+
 # Prettify all staged .js files
-echo "$jsfiles" | xargs ./node_modules/.bin/prettier-eslint --eslint-config-path ./.eslintrc.json --config ./.prettierrc.json --write
+echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier-eslint --eslint-config-path ./.eslintrc.json --config ./.prettierrc.json --list-different --write
 
 # Add back the modified/prettified files to staging
-echo "$jsfiles" | xargs git add
+echo "$STAGED_FILES" | xargs git add
 
 exit 0
+
